### ISSUE TITLE
can't find 'ckpts/instructblip-vicuna-7b'

### ISSUE THREAD

**Issue by ontheway-arch** [bigai-nlco/VideoTGB#1]
in demo.py
model_base = 'ckpts/instructblip-vicuna-7b'
sampler_model_base = 'ckpts/bert-base-uncased'
Are these two weight files downloaded from https://huggingface.co/Salesforce/instructblip-vicuna-7b and https://huggingface.co/google-bert/bert-base-uncased?

**Comment by patrick-tssn** [comment]
Yes,  I apologize for the lack of a proper introduction.
