### ISSUE TITLE
of extraction

### ISSUE THREAD

**Issue by st-fei** [bigai-nlco/VideoTGB#2]
作者您好，我注意到您的工作中使用了光流模态，我尝试从长视频中提取光流，但是其耗时较长，存储成本较高。想请问您是否对长视频作了特殊的处理，谢谢 -v-

**Comment by patrick-tssn** [comment]
抱歉现在才注意到这个issue，我们对视频限制了最大帧数，参考 eval/utils/builder_utils.py 中的 get_frame() 函数；此外，为了加速训练，我们对视频压缩到2fps，压缩工具可以参考：https://github.com/jayleicn/singularity/blob/main/preprocess/compress.py
