### ISSUE TITLE
No gt_file_question

### ISSUE THREAD

**Issue by zli999** [bigai-nlco/VideoTGB#3]
Have you processed the original question files and output the new test_q.json and test_a.json files?

If yes, could you please provide the test_q.json and test_a.json files?
Or the process.py file to process the original datasets.

Thank you!

**Comment by patrick-tssn** [comment]
Sorry for the late reply. Please forgive me, as I didn't receive any notification. The evaluation data are from VideoChatGPT and Video-LLaVA, which can be obtained directly from this [link](https://github.com/PKU-YuanGroup/Video-LLaVA/blob/main/TRAIN_AND_VALIDATE.md#data-for-validating).
