### ISSUE TITLE
Computing Resources

### ISSUE THREAD

**Issue by onion-lynn** [bigai-nlco/VideoTGB#4]
Excellent work! I would like to ask, what is the minimum computing resources required for this project?

**Comment by patrick-tssn** [comment]
It depends on the LLM you selected. In practice, I have only tested models of 7B and smaller on at least two 80G GPUs. Additionally, I'm certain that the distribution strategy (fsdp) of Lightning in this version will encounter oom issues when using 13B models.

**Comment by onion-lynn** [comment]
OK, thanks for your reply！
