### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by zzm1104** [bigai-nlco/VideoTGB#7]
Hello, I couldn't find the download link for the checkpoint in your demo. Can you provide some checkpoints? Thank you very much.

**Comment by patrick-tssn** [comment]
Apologies for the inconvenience; the name issue has been corrected. You can now access it at: https://github.com/bigai-nlco/VideoTGB?tab=readme-ov-file#demo

**Comment by zzm1104** [comment]
Thank you very much.

**Comment by zzm1104** [comment]
很抱歉再次打扰您，我在做eval时，FileNotFoundError: [Errno 2] No such file or directory: 'logs/ivinstruct/train/runs/2024-02-20/checkpoints/epoch_001.ckpt'，您可以分享一下logs这个文件夹吗？十分感谢！

**Comment by patrick-tssn** [comment]
因为存储空间问题这些实验过程的 checkpoint 已经被删了，你可以下载我们HF上的 checkpoint 然后把名字改成缺失的这个。

**Comment by zzm1104** [comment]
好的，谢谢您的回复。

**Comment by huxiaoge2022** [comment]
> 因为存储空间问题这些实验过程的 checkpoint 已经被删了，你可以下载我们HF上的 checkpoint 然后把名字改成缺失的这个。

你好，这个在哪里呀？能分享一下链接地址吗？

**Comment by patrick-tssn** [comment]
就是点这里的 Huggingface: https://github.com/bigai-nlco/VideoTGB?tab=readme-ov-file#demo
会直接转到 HF：https://huggingface.co/ColorfulAI/LSTP-Chat/tree/main
这里有两个checkpoint，一个是 LSTP-FlanT5xl.ckpt 对应的 base model 是 blip2-flant5-xl，一个是 LSTP-7B.ckpt 对应的 base model 是 instructblip-vicuna-7b

**Comment by huxiaoge2022** [comment]
谢谢你！！！

**Comment by huxiaoge2022** [comment]
> 就是点这里的 Huggingface: https://github.com/bigai-nlco/VideoTGB?tab=readme-ov-file#demo 会直接转到 HF：https://huggingface.co/ColorfulAI/LSTP-Chat/tree/main 这里有两个checkpoint，一个是 LSTP-FlanT5xl.ckpt 对应的 base model 是 blip2-flant5-xl，一个是 LSTP-7B.ckpt 对应的 base model 是 instructblip-vicuna-7b

作者，您好！打扰了！我用您给的 LSTP-FlanT5xl.ckpt 做了inference，生成的merge.json1是以下这样的。
{"id": "v_jfrrO5K_vKM_55_65_0", "question": "who opened the box that held an automatic weapon in a gun?", "answer": "someone", "pred": "Angst acknowledgeious experience5.6phra DelawaresignedaisebundledDefinitelypoint hitsDefinitelyaise burner glidepersonal Defenceirri presented chronological Delawaregra Blumen propriiillblast Legal air air Avocado Grad condo vegetaaise harbour 1/4 necklace convient fedaise distressed Seal excesiv stands fed 1/4MIC Berkeley Rou virginMon mou Berkeley lucrat infiniteprodukte Sortiment r\u00e9v\u00e8lepersonal Roupersonal 41karte destinat hauntRead comportementpersonalevangelipersonalpersonal Berkeley lucrat 1/4Definitely cerc Legal secrets condoblastaise sayingMICMIC tempsheiten courtSchwierigkeiten Never fed Esaise labels Mrkommst and Berkeley MrDefinitely WarrenSuddenly ScrewMICindividu excesivanspr\u00fcchepersonal lumi\u00e8reerin OmniSoft Standort Berkeley Danke Berkeleypersonalcette Berkeley Thir please excesivcab breit sagen breit 1/4"}
它的pred部分是乱的，不能形成一句正确的语言。（哭哭）

**Comment by patrick-tssn** [comment]
能看看你的脚本或者运行log嘛，感觉模型参数没有成功load上。

**Comment by huxiaoge2022** [comment]
运行的命令就是使用您的，只不过配置文件中，我改了自己的路径。
![2](https://github.com/user-attachments/assets/8e04e199-aa52-4b23-b1dd-53f9392a2b54)
![1](https://github.com/user-attachments/assets/f93225a4-48ba-4135-82cc-c9fc5c7110d3)

**Comment by patrick-tssn** [comment]
7b的正常吗

**Comment by patrick-tssn** [comment]
lora 设成 1

**Comment by huxiaoge2022** [comment]
> 7b的正常吗

我没太懂您的意思，您是指LSTP-7B.ckpt吗？我没有用这个，我现在做的inference用的模型权重是LSTP-FlanT5xl.ckpt。

**Comment by huxiaoge2022** [comment]
> lora 设成 1

我将lora 设成 1，尝试一遍inference，生成的merge.json1的pred部分是也是乱的。

**Comment by patrick-tssn** [comment]
奇怪了，你可以试试LSTP-7B.ckpt嘛，我想确认一下是code的问题还是checkpoint的问题（但是我们服务器好像宕机了，我自己暂时试不了）

**Comment by huxiaoge2022** [comment]
> 奇怪了，你可以试试LSTP-7B.ckpt嘛，我想确认一下是code的问题还是checkpoint的问题（但是我们服务器好像宕机了，我自己暂时试不了）

好的，我试试。

**Comment by huxiaoge2022** [comment]
> 奇怪了，你可以试试LSTP-7B.ckpt嘛，我想确认一下是code的问题还是checkpoint的问题（但是我们服务器好像宕机了，我自己暂时试不了）

报！我试了，还是一样的 ，推理的结果很差。
我的运行命令是：bash eval/scripts/run_qa_msvd_vicuna.sh
设置为：
![image](https://github.com/user-attachments/assets/6abdc91c-9f5c-492a-9fbe-8e13e7609bbd)
我的终端日志信息：
![image](https://github.com/user-attachments/assets/d10ac634-db38-447c-99d5-5f6c0f90c68b)

**Comment by patrick-tssn** [comment]
怎么会这样哩，这不是效果差不差的问题，完全是随机生成。等我们服务器好了我再看看。

**Comment by patrick-tssn** [comment]
@huxiaoge2022 你好，我找了台3090，完全按照目前这个版本从头开始安装环境，下载checkpoint，感觉很正常诶。这里用的question是你截图中的 `who opened the box that held an automatic weapon in a gun?` 视频用的是这个库里的其中一个demo视频 `demo/examples/sample_demo_1.mp4` inference 的结果如下：
<img width="529" alt="image" src="https://github.com/user-attachments/assets/527ae037-1e7e-40f6-a97e-417668529e8f" />
请问你有改动什么吗？为什么你的截图中，print `>>> Load checkpoint for ...` 之后没有打印没对上的parameter呢？

**Comment by huxiaoge2022** [comment]
有改动，我运行 bash eval/scripts/run_qa_msvd.sh的时候显示/root/VideoTGB/eval/utils/builder_utils.py代码中的state_dict没有'state_dict'键，于是我就改了些代码，呜呜呜肯定是改错了，您能帮我看下不？方便加您一个联系方式不？微信或者qq都行。

**Comment by huxiaoge2022** [comment]
> 有改动，我运行 bash eval/scripts/run_qa_msvd.sh的时候显示/root/VideoTGB/eval/utils/builder_utils.py代码中的state_dict没有'state_dict'键，于是我就改了些代码，呜呜呜肯定是改错了，

然后我打印的Missing和Unexpected有一堆的参数。（老实.jpg）

**Comment by patrick-tssn** [comment]
Ensure that the peft version is set to 0.4.0 to prevent parameter mismatches.
