### ISSUE TITLE
pseudo_label

### ISSUE THREAD

**Issue by huxiaoge2022** [bigai-nlco/VideoTGB#8]
作者大大，您好，我又来了，我想请教一下您，生成的伪标签的数据应该是什么样的呀？
    {
        "video_id": "v_GqWH2IYPw6U",
        "query": "Is the mime the only person who does something other than singing?",
        "answer": "Yes, the mime walks in with fireworks while the group still sings and many around are seen laughing and smiling.",
        "score_best": 0,
        "start_index": 0,
        "end_index": 96
    },
    这是我生成的伪标签的数据，是不是不对？

**Comment by patrick-tssn** [comment]
看起来没啥问题，我的文件格式就是一个 dict(list): value 用一个 list 保存 start & end index，感觉你这样更清楚。
`{"1": [0, 17], "3": [2, 31],...}`

比如：https://www.alipan.com/s/RjwRQsYjXyk

**Comment by huxiaoge2022** [comment]
好的好的，感谢！！！您真是个大好人，人又好能力又强！！！能不能请您提供一下生成伪标签的代码呀？我写的有问题，我所有的"start_index"都是0。

**Comment by patrick-tssn** [comment]
就是我上次 refer 的那一段，我记得有好多 data 上我也是 start_index 都是0，特别是那种区别不大的视频，因为这种 general instruction data 不太需要 temporal grounding，我觉得问题不大。如果你不放心可以在那个上面改一改，比如加一个用 sliding window 用来做平滑的 trick

**Comment by huxiaoge2022** [comment]
好的，谢谢你！！！
