### ISSUE TITLE
pseudo_label

### ISSUE THREAD

**Issue by huxiaoge2022** [bigai-nlco/VideoTGB#9]
呜呜呜呜呜呜呜，作者，您好，我又又又又来了。
我伪标签终于生成啦，但是效果不好。
想请教一下您，我该用哪些方法来提升我的生成效果呢？
比如：
1、您用什么大模型来生成基于query的预测？
2、您用什么相似度度量来计算预测与answer之间的相似度？
3、采用什么样的提取视频帧的策略？
谢谢您，感激不尽！！！！
![f4292df448347a2a0f0eef439a36d5b](https://github.com/user-attachments/assets/164ea608-0dda-4ef0-9e9a-cae64b61e3a6)

**Comment by patrick-tssn** [comment]
1. 我当时用的是 Blip2-flant5-xl 和 InstructBlip-Vicuna7b，对应的大模型是 FlanT5-xl 和 Vicuna-7b-1.5，不过现在有点过时了，我建议用最新的Llama3.2, Qwen2.5
2. 我用的是 Rouge-1
3. 采样就根据计算资源，我当时用的是2秒一帧，外加最大帧数128的限制。
效果不好我觉得主要是data的问题，我觉得可以在temporal grounding更强的数据上试一试，比如一些Action Localization的数据集，Coin, QVHighlight 等等。算法上，相似度你也可以试试别的，比如 Bertsore, GPTscore 这种 semantic 上的指标。

**Comment by huxiaoge2022** [comment]
好的，谢谢你！！！

**Comment by huxiaoge2022** [comment]
作者，您好。请问，如果我生成伪标签时使用2秒一帧，那我提取光流时是否也需要设置为2秒一帧呢？

**Comment by patrick-tssn** [comment]
这个倒不用，这些都可以按比例换算的。

**Comment by huxiaoge2022** [comment]
好的，谢谢你！我还有个问题，那个最大帧数的限制是依据什么来设定的呢？是视频时长吗？如果是2秒一帧，2 x 128 = 256 秒，也就是视频时长最多取到256秒吗？再长的视频，后面就不在取帧了是吗？

**Comment by patrick-tssn** [comment]
最大帧数就是显存限制的，因为每一帧都要decode才能做别的。一般不会直接截断，还是会采样，比如512秒的视频按fps=0.5有256帧，还是强行均匀采样到128帧（一般用numpy的linspace采），当然也可以改fps，这些都是资源限制下的操作，按实际情况处理就行。

**Comment by huxiaoge2022** [comment]
明白了，谢谢！！！
![微信图片_20241211205606](https://github.com/user-attachments/assets/1bc8bc4b-3086-4995-bc04-0d734dae164e)
